[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bench_runner"
authors = [
    {name = "Michael Droettboom", email = "mdroettboom@microsoft.com"},
]
description = "Faster CPython's benchmarking runner utilities"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ijson==3.3.0",
    "matplotlib==3.9.0",
    "pyperf@git+https://github.com/psf/pyperf#egg=2b9591dcc5be28998d29237f6665b30ca2e1b805",
    "rich==13.7.1",
    "rich-argparse==1.5.1",
    "ruamel.yaml==0.18.6",
    "ujson==5.10.0",
    "wheel",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "black==24.4.2",
    "flake8==7.0.0",
    "pyright==1.1.366",
    "pytest==8.2.2",
]

[tool.setuptools_scm]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
bench_runner = ["templates/*"]
