---
name: _publish

"on":
  workflow_call:
    inputs:
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout benchmarking-public
        uses: actions/checkout@v4
        with:
          path: public
          ref: main
          repository: ${{ github.repository }}-public
          token: ${{ secrets.BENCHMARK_MIRROR }}
      - name: Mirror
        run: |
          cd public
          git remote add upstream https://github.com/faster-cpython/benchmarking
          git fetch upstream
          git reset --hard upstream/main
      - name: Push
        if: ${{ !inputs.dry_run }}
        run: |
          cd public
          git push origin main
