---
name: _publish

"on":
  workflow_call:
    inputs:
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout benchmarking
        uses: actions/checkout@v4
        with:
          ref: main
          # This has to be enough depth to handle since the last time we published.
          # As a rule of thumb, (number of machines * 2, plus the generated stuff) * 2
          fetch-depth: 20
      - name: Mirror
        run: |
          git remote add public https://${{ secrets.BENCHMARK_MIRROR }}@github.com/${{ github.repository }}-public
          git push -f public main
