---
name: _publish

"on":
  workflow_call:
    inputs:
      dry_run:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run: Do not commit to the repo"
        type: boolean
        default: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout benchmarking
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Mirror
        run: |
          gh repo sync ${{ github.repository }}-public
        env:
          GH_TOKEN: ${{ secrets.BENCHMARK_MIRROR }}
